/**
 * Bill Category Mapping Config — extracted from bills.tsx route
 * to avoid cross-route imports that break TanStack Start server functions.
 */
import type { MappingConfig } from "./coa/mapping-types";

export const BILL_MAPPING_CONFIG: MappingConfig = {
  storageKey: "digits:bill-category-mappings",
  mappingType: "bill",
  title: "Bill Category Mapping",
  description: "Choose default ledger accounts for bill line items and payables",
  rows: [
    {
      type: "default_expense",
      label: "Default Expense",
      icon: "📋",
      ledgerType: "expense",
      defaultSubtype: "uncategorized_expenses",
      defaultName: "Uncategorized Expenses",
      defaultNumber: "69999",
    },
    {
      type: "accounts_payable",
      label: "Accounts Payable",
      icon: "💳",
      ledgerType: "liability",
      defaultSubtype: "accounts_payable",
      defaultName: "Accounts Payable",
      defaultNumber: "21000",
    },
    {
      type: "facilities",
      label: "Facilities",
      icon: "🏢",
      ledgerType: "expense",
      defaultSubtype: "facilities",
      defaultName: "Facilities",
      defaultNumber: "66000",
    },
    {
      type: "general_operations",
      label: "General Operations",
      icon: "⚙️",
      ledgerType: "expense",
      defaultSubtype: "general_operations",
      defaultName: "General Operations",
      defaultNumber: "68000",
    },
    {
      type: "insurance",
      label: "Insurance",
      icon: "🛡️",
      ledgerType: "expense",
      defaultSubtype: "insurance",
      defaultName: "Insurance",
      defaultNumber: "68200",
    },
    {
      type: "supplies_and_materials",
      label: "Supplies & Materials",
      icon: "📎",
      ledgerType: "expense",
      defaultSubtype: "supplies_and_materials",
      defaultName: "Supplies & Materials",
      defaultNumber: "67000",
    },
    {
      type: "professional_fees",
      label: "Professional Fees",
      icon: "👔",
      ledgerType: "expense",
      defaultSubtype: "professional_fees",
      defaultName: "Professional Fees",
      defaultNumber: "63000",
    },
    {
      type: "business_application_software",
      label: "Software & Subscriptions",
      icon: "💻",
      ledgerType: "expense",
      defaultSubtype: "business_application_software",
      defaultName: "Software & Subscriptions",
      defaultNumber: "65000",
    },
    // ─── Cost of Revenue (COGS) ───
    {
      type: "payment_processing_fees",
      label: "Payment Processing",
      icon: "💳",
      ledgerType: "cost_of_revenue",
      defaultSubtype: "payment_processing_fees",
      defaultName: "Payment Processing Fees",
      defaultNumber: "53000",
    },
    {
      type: "hosting_fees",
      label: "Hosting Fees",
      icon: "🖥️",
      ledgerType: "cost_of_revenue",
      defaultSubtype: "hosting_fees",
      defaultName: "Hosting Fees",
      defaultNumber: "54000",
    },
    {
      type: "cost_of_goods",
      label: "Cost of Goods",
      icon: "📦",
      ledgerType: "cost_of_revenue",
      defaultSubtype: "cost_of_goods",
      defaultName: "Cost of Goods",
      defaultNumber: "51000",
    },
    // ─── Other Expenses ───
    {
      type: "taxes",
      label: "Taxes",
      icon: "🏛️",
      ledgerType: "other_expense",
      defaultSubtype: "taxes",
      defaultName: "Taxes",
      defaultNumber: "94000",
    },
    {
      type: "interest_expense",
      label: "Interest Expense",
      icon: "📈",
      ledgerType: "other_expense",
      defaultSubtype: "interest_expense",
      defaultName: "Interest Expense",
      defaultNumber: "91000",
    },
    {
      type: "other_miscellaneous_expenses",
      label: "Other Expenses",
      icon: "📂",
      ledgerType: "other_expense",
      defaultSubtype: "other_miscellaneous_expenses",
      defaultName: "Other Expenses",
      defaultNumber: "92000",
    },
    // ─── Uncategorized ───
    {
      type: "other_current_liabilities",
      label: "Other Current Liabilities",
      icon: "❓",
      ledgerType: "liability",
      defaultSubtype: "other_current_liabilities",
      defaultName: "Other Current Liabilities",
      defaultNumber: "25000",
    },
  ],
};
