/**
 * The baseline chart of accounts.
 *
 * Lifted from the original `scripts/seed-coa.ts` CATEGORY_TREE, with stable
 * `key`s added and five accounts the seed was missing. Three of those are
 * load-bearing: without `refunds_discounts` and a sales-tax liability the
 * invoice resolvers throw on every freshly created org, and without an
 * `other_miscellaneous_expenses` account the bill mapping of the same name has
 * nothing to point at.
 *
 * Numbering follows ACCOUNT_TYPE_RANGES: 10000 assets, 20000 liabilities,
 * 30000 equity, 40000 revenue, 50000 cost of revenue, 60000 operating
 * expenses, 80000 other income, 90000 other expenses.
 *
 * Every other preset is expressed as a diff on top of this tree.
 */
import type { PresetAccount } from "../preset-types";

export const BASE_ACCOUNTS: readonly PresetAccount[] = [
  {
    key: "assets",
    name: "Assets",
    accountNumber: "10000",
    accountType: "asset",
    subtype: null,
    icon: "Wallet",
    description:
      "Resources owned by a company that are expected to provide future economic benefits",
    isSystem: true,
    children: [
      {
        key: "bank_accounts",
        name: "Bank Accounts",
        accountNumber: "11000",
        accountType: "asset",
        subtype: "bank_accounts",
        icon: "Bank",
        description:
          "Operating cash accounts at financial institutions used for daily transactions",
      },
      {
        key: "asset_clearing",
        name: "Asset Clearing",
        accountNumber: "11500",
        accountType: "asset",
        subtype: "asset_clearing",
        icon: "ArrowSwitch",
        description: "Temporary clearing accounts used for asset transfers in process",
      },
      {
        key: "accounts_receivable",
        name: "Accounts Receivable",
        accountNumber: "12000",
        accountType: "asset",
        subtype: "account_receivable",
        icon: "CoinsHand",
        description: "Money owed to the company by its customers for goods or services delivered",
        children: [
          {
            key: "accounts_receivable_gross",
            name: "Accounts Receivable - Gross",
            accountNumber: "12010",
            accountType: "asset",
            subtype: "account_receivable",
            icon: "CoinsHand",
            description:
              "Total outstanding invoiced amounts before allowance for doubtful accounts",
          },
        ],
      },
      {
        key: "prepaid_expenses",
        name: "Prepaid Expenses",
        accountNumber: "13000",
        accountType: "asset",
        subtype: "prepaid_expenses",
        icon: "CalendarDollar01",
        description:
          "Payments made in advance for goods or services that will be received in the future",
      },
      {
        key: "investments",
        name: "Investments",
        accountNumber: "14000",
        accountType: "asset",
        subtype: "investments",
        icon: "TrendUp01",
        description: "Short-term investments in stocks and other marketable securities",
      },
      {
        key: "shareholder_loans",
        name: "Shareholder Loans",
        accountNumber: "14500",
        accountType: "asset",
        subtype: "shareholder_loans",
        icon: "Shareholders",
        description: "Loans made by the company to its shareholders or related parties",
      },
      {
        key: "uncategorized_assets",
        name: "Uncategorized Assets",
        accountNumber: "15999",
        accountType: "asset",
        subtype: "uncategorized_assets",
        icon: "QuestionTransaction",
        description: "Default bucket for asset transactions that have not yet been categorized",
      },
      {
        key: "fixed_assets",
        name: "Fixed Assets",
        accountNumber: "16000",
        accountType: "asset",
        subtype: "fixed_assets",
        icon: "Couch",
        description:
          "Long-term tangible assets used in business operations (property, plant, equipment)",
        children: [
          {
            key: "computer_assets",
            name: "Computer Assets",
            accountNumber: "16100",
            accountType: "asset",
            subtype: "fixed_assets",
            icon: "ComputerAsset",
            description:
              "Gross cost of all computer hardware and equipment such as laptops and monitors",
          },
        ],
      },
      {
        key: "inventory",
        name: "Inventory",
        accountNumber: "13500",
        accountType: "asset",
        subtype: "inventory",
        icon: "Package",
        description: "Goods held for resale, valued at cost",
      },
    ],
  },
  {
    key: "liabilities",
    name: "Liabilities",
    accountNumber: "20000",
    accountType: "liability",
    subtype: null,
    icon: "Iou",
    description: "Financial obligations or debts owed to external parties",
    isSystem: true,
    children: [
      {
        key: "accounts_payable",
        name: "Accounts Payable",
        accountNumber: "21000",
        accountType: "liability",
        subtype: "accounts_payable",
        icon: "CoinsHand02",
        description:
          "Amounts owed to suppliers and vendors for goods and services already received",
      },
      {
        key: "credit_cards",
        name: "Credit Cards",
        accountNumber: "22000",
        accountType: "liability",
        subtype: "credit_cards",
        icon: "CreditCard",
        description: "Balances due on company-issued or business credit card accounts",
      },
      {
        key: "liability_clearing",
        name: "Liability Clearing",
        accountNumber: "23000",
        accountType: "liability",
        subtype: "liability_clearing",
        icon: "ArrowSwitch",
        description: "Temporary clearing accounts for liability transactions in transit",
        children: [
          {
            key: "payroll_clearing",
            name: "Payroll Clearing",
            accountNumber: "23200",
            accountType: "liability",
            subtype: "liability_clearing",
            icon: "PayrollClearing",
            description: "Temporary clearing account to track payroll payments in transit",
          },
          {
            key: "bill_pay_clearing",
            name: "Bill Pay Clearing",
            accountNumber: "23300",
            accountType: "liability",
            subtype: "liability_clearing",
            icon: "BillClearing",
            description: "Temporary clearing account to track bill payments in transit",
          },
        ],
      },
      {
        key: "accrued_expenses",
        name: "Accrued Expenses",
        accountNumber: "24000",
        accountType: "liability",
        subtype: "accrued_expenses",
        icon: "CalendarDollar01",
        description: "Expenses incurred but not yet paid, such as employee bonuses",
      },
      {
        key: "other_current_liabilities",
        name: "Other Current Liabilities",
        accountNumber: "25000",
        accountType: "liability",
        subtype: "other_current_liabilities",
        icon: "Iou",
        description: "Short-term obligations not classified in other liability categories",
        children: [
          {
            key: "uncategorized_liabilities",
            name: "Uncategorized Liabilities",
            accountNumber: "25066",
            accountType: "liability",
            subtype: "other_current_liabilities",
            icon: "QuestionTransaction",
            description:
              "Default bucket for liability transactions that have not yet been categorized",
          },
        ],
      },
      {
        key: "payroll_liabilities",
        name: "Payroll Liabilities",
        accountNumber: "25100",
        accountType: "liability",
        subtype: "payroll_liabilities",
        icon: "UserCoins01",
        description: "Amounts owed for employee wages, taxes, and benefits",
      },
      {
        key: "sales_tax_payable",
        name: "Sales Tax Payable",
        accountNumber: "21500",
        accountType: "liability",
        subtype: "other_current_liabilities",
        icon: "Bank",
        description: "Sales tax collected from customers and owed to tax authorities",
      },
      {
        key: "deferred_revenue",
        name: "Deferred Revenue",
        accountNumber: "26000",
        accountType: "liability",
        subtype: "deferred_revenue",
        icon: "Calendar",
        description: "Payments received for goods or services not yet delivered",
      },
    ],
  },
  {
    key: "equity",
    name: "Equity",
    accountNumber: "30000",
    accountType: "equity",
    subtype: null,
    icon: "Certificate01",
    description: "The residual interest in assets after deducting liabilities (net worth)",
    isSystem: true,
    children: [
      {
        key: "retained_earnings",
        name: "Retained Earnings",
        accountNumber: "31000",
        accountType: "equity",
        subtype: "retained_earnings",
        icon: "BankDollar",
        description:
          "Cumulative net income retained in the business and not distributed as dividends",
      },
      {
        key: "owners_equity",
        name: "Owners Equity",
        accountNumber: "32000",
        accountType: "equity",
        subtype: "owners_equity",
        icon: "Consultant",
        description:
          "Capital contributed by and distributions to owners, partners, or shareholders",
      },
      {
        key: "safes",
        name: "SAFEs",
        accountNumber: "33000",
        accountType: "equity",
        subtype: "safes",
        icon: "Award03",
        description: "Simple Agreements for Future Equity — convertible instruments from investors",
      },
    ],
  },
  {
    key: "revenue",
    name: "Revenue",
    accountNumber: "40000",
    accountType: "revenue",
    subtype: null,
    icon: "SvgTagDollar",
    description: "Income earned from the company's primary business operations",
    isSystem: true,
    children: [
      {
        key: "sales_revenue",
        name: "Sales Revenue",
        accountNumber: "41000",
        accountType: "revenue",
        subtype: "sales_revenue",
        icon: "SvgTagDollar",
        description: "Income from direct sale of products, merchandise, or one-time services",
      },
      {
        key: "subscription_revenue",
        name: "Subscription Revenue",
        accountNumber: "42000",
        accountType: "revenue",
        subtype: "subscription_revenue",
        icon: "SubscriptionRevenue",
        description:
          "Recurring income from subscription-based products or services (SaaS, memberships)",
      },
      {
        key: "transaction_revenue",
        name: "Transaction Revenue",
        accountNumber: "43000",
        accountType: "revenue",
        subtype: "transaction_revenue",
        icon: "Transaction",
        description:
          "Income earned on a per-transaction basis such as payment processing or marketplace fees",
      },
      {
        key: "refunds_and_discounts",
        name: "Refunds & Discounts",
        accountNumber: "49000",
        accountType: "revenue",
        subtype: "refunds_discounts",
        icon: "QuestionTransaction",
        description: "Contra-revenue for customer refunds, credits, and discounts given",
      },
    ],
  },
  {
    key: "cost_of_revenue",
    name: "Cost of Revenue",
    accountNumber: "50000",
    accountType: "cost_of_revenue",
    subtype: null,
    icon: "BagDollar01",
    description: "Direct costs attributable to the production of goods or services sold",
    isSystem: true,
    children: [
      {
        key: "cost_of_goods_sold",
        name: "Cost of Goods Sold",
        accountNumber: "51000",
        accountType: "cost_of_revenue",
        subtype: "cost_of_goods",
        icon: "BankNoteScissors01",
        description:
          "Direct material and labor costs for producing or purchasing goods that were sold",
      },
      {
        key: "payment_processing_fees",
        name: "Payment Processing Fees",
        accountNumber: "53000",
        accountType: "cost_of_revenue",
        subtype: "payment_processing_fees",
        icon: "PaymentProcessingFee",
        description:
          "Fees charged by payment processors (Stripe, PayPal) for processing customer payments",
      },
      {
        key: "hosting_fees",
        name: "Hosting Fees",
        accountNumber: "54000",
        accountType: "cost_of_revenue",
        subtype: "hosting_fees",
        icon: "HostingFee",
        description:
          "Cloud infrastructure and hosting costs directly supporting the product (AWS, GCP, Azure)",
      },
    ],
  },
  {
    key: "operating_expenses",
    name: "Operating Expenses",
    accountNumber: "60000",
    accountType: "expense",
    subtype: null,
    icon: "Opex",
    description:
      "Ongoing costs required to run the business that are not directly tied to a product or service",
    isSystem: true,
    children: [
      {
        key: "payroll_expenses",
        name: "Payroll Expenses",
        accountNumber: "61000",
        accountType: "expense",
        subtype: "payroll_expenses",
        icon: "Salary",
        description: "All compensation-related costs including wages, benefits, and employer taxes",
        children: [
          {
            key: "salaries",
            name: "Salaries",
            accountNumber: "61100",
            accountType: "expense",
            subtype: "payroll_expenses",
            icon: "Salary",
            description: "Base salaries and wages paid to full-time and part-time employees",
          },
          {
            key: "employee_benefits",
            name: "Employee Benefits",
            accountNumber: "61400",
            accountType: "expense",
            subtype: "payroll_expenses",
            icon: "Salary",
            description:
              "Health insurance, dental, vision, and other employer-sponsored benefit costs",
          },
          {
            key: "retirement_contributions",
            name: "Retirement Contributions",
            accountNumber: "61500",
            accountType: "expense",
            subtype: "payroll_expenses",
            icon: "Retirement",
            description:
              "Employer matching or contributions to 401k, IRA, or other retirement plans",
          },
          {
            key: "employer_payroll_taxes",
            name: "Employer Payroll Taxes",
            accountNumber: "61600",
            accountType: "expense",
            subtype: "payroll_expenses",
            icon: "Salary",
            description:
              "Employer portion of Social Security, Medicare, FUTA, and state unemployment taxes",
          },
          {
            key: "payroll_processing_fees",
            name: "Payroll Processing Fees",
            accountNumber: "61700",
            accountType: "expense",
            subtype: "payroll_expenses",
            icon: "BankNoteScissors01",
            description:
              "Fees charged by payroll providers (Gusto, ADP) for processing employee payroll",
          },
        ],
      },
      {
        key: "travel_and_entertainment",
        name: "Travel & Entertainment",
        accountNumber: "62000",
        accountType: "expense",
        subtype: "travel_entertainment",
        icon: "Travel",
        description:
          "Costs for business travel and entertainment activities including airfare, hotels, and meals",
        children: [
          {
            key: "airfare",
            name: "Airfare",
            accountNumber: "62100",
            accountType: "expense",
            subtype: "travel_entertainment",
            icon: "Travel",
            description: "Airline tickets and related booking fees for business travel",
          },
          {
            key: "ground_transportation",
            name: "Ground Transportation",
            accountNumber: "62200",
            accountType: "expense",
            subtype: "travel_entertainment",
            icon: "Car",
            description:
              "Ride-shares, car rentals, taxis, and mileage reimbursements for business travel",
          },
          {
            key: "lodging",
            name: "Lodging",
            accountNumber: "62300",
            accountType: "expense",
            subtype: "travel_entertainment",
            icon: "Lodge",
            description: "Hotel stays and other lodging costs incurred during business travel",
          },
          {
            key: "meals",
            name: "Meals",
            accountNumber: "62400",
            accountType: "expense",
            subtype: "travel_entertainment",
            icon: "Meals",
            description:
              "Meals with clients, team meals, and per diem food costs during business travel",
          },
          {
            key: "entertainment",
            name: "Entertainment",
            accountNumber: "62500",
            accountType: "expense",
            subtype: "travel_entertainment",
            icon: "Music",
            description:
              "Client entertainment, team outings, and recreational events for business purposes",
          },
        ],
      },
      {
        key: "professional_fees",
        name: "Professional Fees",
        accountNumber: "63000",
        accountType: "expense",
        subtype: "professional_fees",
        icon: "Award03",
        description:
          "Fees paid to external professionals for specialized services such as legal, accounting, and consulting",
        children: [
          {
            key: "consultants_and_contractors",
            name: "Consultants and Contractors",
            accountNumber: "63100",
            accountType: "expense",
            subtype: "professional_fees",
            icon: "Consultant",
            description: "Fees paid to independent advisors, freelancers, and consulting firms",
          },
          {
            key: "legal",
            name: "Legal",
            accountNumber: "63200",
            accountType: "expense",
            subtype: "professional_fees",
            icon: "Legal",
            description: "Legal counsel, contract review, IP protection, and compliance costs",
          },
          {
            key: "tax_and_accounting",
            name: "Tax & Accounting",
            accountNumber: "63300",
            accountType: "expense",
            subtype: "professional_fees",
            icon: "Accounting01",
            description: "External accountant, tax preparation, and audit fees",
          },
          {
            key: "other_professional_fees",
            name: "Other Professional Fees",
            accountNumber: "63400",
            accountType: "expense",
            subtype: "professional_fees",
            icon: "Award03",
            description:
              "Miscellaneous professional services not classified elsewhere (e.g. recruiting, advisory)",
          },
        ],
      },
      {
        key: "sales_and_marketing",
        name: "Sales and Marketing",
        accountNumber: "64000",
        accountType: "expense",
        subtype: "sales_marketing",
        icon: "Announcement04",
        description:
          "Costs related to promoting, advertising, and selling the company's products or services",
        children: [
          {
            key: "advertising",
            name: "Advertising",
            accountNumber: "64100",
            accountType: "expense",
            subtype: "sales_marketing",
            icon: "Advertising",
            description: "Paid media (Google Ads, Facebook, LinkedIn) and display advertising",
          },
          {
            key: "conference_and_trade_shows",
            name: "Conference and Trade Shows",
            accountNumber: "64200",
            accountType: "expense",
            subtype: "sales_marketing",
            icon: "Conference",
            description:
              "Booth fees, travel, and materials for industry conferences, expos, and trade shows",
          },
          {
            key: "promotional_items_and_gifts",
            name: "Promotional Items and Gifts",
            accountNumber: "64300",
            accountType: "expense",
            subtype: "sales_marketing",
            icon: "Gift",
            description:
              "Branded merchandise, customer gifts, and swag used for marketing and retention",
          },
        ],
      },
      {
        key: "business_applications_and_software",
        name: "Business Applications & Software",
        accountNumber: "65000",
        accountType: "expense",
        subtype: "business_application_software",
        icon: "Apps",
        description:
          "SaaS subscriptions and software licenses for internal business operations (Slack, Notion, etc.)",
      },
      {
        key: "facilities",
        name: "Facilities",
        accountNumber: "66000",
        accountType: "expense",
        subtype: "facilities",
        icon: "Facilities",
        description:
          "Costs associated with operating and maintaining the company's physical workspace",
        children: [
          {
            key: "rent",
            name: "Rent",
            accountNumber: "66100",
            accountType: "expense",
            subtype: "facilities",
            icon: "Rent",
            description:
              "Monthly lease payments for office space, co-working desks, or warehouse facilities",
          },
          {
            key: "utilities",
            name: "Utilities",
            accountNumber: "66200",
            accountType: "expense",
            subtype: "facilities",
            icon: "Utilities",
            description:
              "Electricity, water, gas, internet, and other utility bills for business premises",
          },
          {
            key: "repairs_and_maintenance",
            name: "Repairs and Maintenance",
            accountNumber: "66300",
            accountType: "expense",
            subtype: "facilities",
            icon: "Repairs",
            description:
              "Costs for repairing and maintaining office equipment, furniture, and facilities",
          },
        ],
      },
      {
        key: "supplies_and_materials",
        name: "Supplies & Materials",
        accountNumber: "67000",
        accountType: "expense",
        subtype: "supplies_and_materials",
        icon: "PaperClip",
        description: "Consumable items and materials used in daily business operations",
        children: [
          {
            key: "computers_expense",
            name: "Computers Expense",
            accountNumber: "67100",
            accountType: "expense",
            subtype: "supplies_and_materials",
            icon: "Computer",
            description:
              "Computer hardware purchases below capitalization threshold (peripherals, accessories)",
          },
          {
            key: "office_supplies",
            name: "Office Supplies",
            accountNumber: "67200",
            accountType: "expense",
            subtype: "supplies_and_materials",
            icon: "PaperClip",
            description:
              "General office consumables — paper, pens, printer toner, desk accessories, etc.",
          },
        ],
      },
      {
        key: "general_operations",
        name: "General Operations",
        accountNumber: "68000",
        accountType: "expense",
        subtype: "general_operations",
        icon: "Operations",
        description: "Miscellaneous operating costs that do not fit into other expense categories",
        children: [
          {
            key: "memberships_and_dues",
            name: "Memberships & Dues",
            accountNumber: "68100",
            accountType: "expense",
            subtype: "general_operations",
            icon: "Membership2",
            description:
              "Professional association memberships, industry dues, and organizational fees",
          },
          {
            key: "insurance",
            name: "Insurance",
            accountNumber: "68200",
            accountType: "expense",
            subtype: "insurance",
            icon: "Insurance",
            description:
              "General liability, D&O, E&O, cyber liability, and other business insurance premiums",
          },
          {
            key: "bank_fees",
            name: "Bank Fees",
            accountNumber: "68300",
            accountType: "expense",
            subtype: "bank_fees",
            icon: "BankNoteScissors01",
            description:
              "Monthly banking fees, wire transfer charges, and other financial institution fees",
          },
        ],
      },
      {
        key: "uncategorized_expense",
        name: "Uncategorized Expense",
        accountNumber: "69999",
        accountType: "expense",
        subtype: "uncategorized_expenses",
        icon: "QuestionTransaction",
        description: "Default bucket for expense transactions that have not yet been categorized",
      },
    ],
  },
  {
    key: "other_income",
    name: "Other Income",
    accountNumber: "80000",
    accountType: "other_income",
    subtype: null,
    icon: "OtherIncome",
    description: "Non-operating income from activities outside the company's core business",
    isSystem: true,
    children: [
      {
        key: "interest_income",
        name: "Interest Income",
        accountNumber: "81000",
        accountType: "other_income",
        subtype: "interests_dividends",
        icon: "Percent",
        description:
          "Interest earned on bank deposits, money market accounts, and other financial instruments",
      },
      {
        key: "credit_card_rewards",
        name: "Credit Card Rewards",
        accountNumber: "82000",
        accountType: "other_income",
        subtype: "credit_card_rewards",
        icon: "CreditCardRewards",
        description:
          "Cash-back rewards, points, and promotional bonuses earned on business credit cards",
      },
    ],
  },
  {
    key: "other_expenses",
    name: "Other Expenses",
    accountNumber: "90000",
    accountType: "other_expense",
    subtype: null,
    icon: "OtherExpenses",
    description:
      "Non-operating costs from activities outside the company's primary business operations",
    isSystem: true,
    children: [
      {
        key: "interest_expense",
        name: "Interest Expense",
        accountNumber: "91000",
        accountType: "other_expense",
        subtype: "interest_expense",
        icon: "Percent",
        description:
          "Interest paid on loans, lines of credit, credit card balances, and other borrowings",
      },
      {
        key: "taxes",
        name: "Taxes",
        accountNumber: "94000",
        accountType: "other_expense",
        subtype: "taxes",
        icon: "CoinsStacked03",
        description: "Income taxes, franchise taxes, and other governmental tax obligations",
      },
      {
        key: "other_miscellaneous_expenses",
        name: "Other Miscellaneous Expenses",
        accountNumber: "92000",
        accountType: "other_expense",
        subtype: "other_miscellaneous_expenses",
        icon: "QuestionTransaction",
        description: "Non-operating expenses that do not fit another category",
      },
    ],
  },
];
