/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AiProposalsRouteImport } from './routes/ai-proposals'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BusinessGroupsRouteImport } from './routes/business-groups'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReconciliationsRouteImport } from './routes/reconciliations'
import { Route as ReviewAgentsRouteImport } from './routes/review-agents'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as BillsBillIdRouteImport } from './routes/bills_.$billId'
import { Route as BillsCreateRouteImport } from './routes/bills_.create'
import { Route as DepartmentsDepartmentIdRouteImport } from './routes/departments_.$departmentId'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents_.$documentId'
import { Route as EntitiesBanksRouteImport } from './routes/entities.banks'
import { Route as EntitiesCustomersRouteImport } from './routes/entities.customers'
import { Route as EntitiesEmployeesRouteImport } from './routes/entities.employees'
import { Route as EntitiesGovernmentRouteImport } from './routes/entities.government'
import { Route as EntitiesLendersRouteImport } from './routes/entities.lenders'
import { Route as EntitiesShareholdersRouteImport } from './routes/entities.shareholders'
import { Route as EntitiesVendorsRouteImport } from './routes/entities.vendors'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices_.$invoiceId'
import { Route as LocationsLocationIdRouteImport } from './routes/locations_.$locationId'
import { Route as OrganizationsJoinRouteImport } from './routes/organizations.join'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as TaxCertificatesRouteImport } from './routes/tax.certificates'
import { Route as PayrollRunIdRouteImport } from './routes/payroll_.$runId'
import { Route as TaxComputeRouteImport } from './routes/tax.compute'
import { Route as TaxSettingsRouteImport } from './routes/tax.settings'
import { Route as TaxDeadlinesRouteImport } from './routes/tax.deadlines'
import { Route as TaxEwtRouteImport } from './routes/tax.ewt'
import { Route as TaxPartiesRouteImport } from './routes/tax.parties'
import { Route as ReconciliationsReconciliationIdRouteImport } from './routes/reconciliations_.$reconciliationId'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions_.$transactionId'
import { Route as TransactionsNewRouteImport } from './routes/transactions_.new'
import { Route as AccountsCategoryCategoryIdRouteImport } from './routes/accounts_/category/$categoryId'
import { Route as EntitiesEntityTypePartyIdRouteImport } from './routes/entities.$entityType.$partyId'
import { Route as EntitiesBanksBankIdRouteImport } from './routes/entities.banks_.$bankId'
import { Route as InvoicesDraftInvoiceIdRouteImport } from './routes/invoices_.draft.$invoiceId'
import { Route as InvoicesDraftCreateRouteImport } from './routes/invoices_.draft.create'
import { Route as InvoicesPayInvoiceIdRouteImport } from './routes/invoices_.pay.$invoiceId'
import { Route as OrganizationOrgIdConnectionsRouteImport } from './routes/organization.$orgId.connections'
import { Route as OrganizationOrgIdMappingsRouteImport } from './routes/organization.$orgId.mappings'
import { Route as OrganizationOrgIdSettingsRouteImport } from './routes/organization.$orgId.settings'
import { Route as InvoicesDraftInvoiceIdReviewRouteImport } from './routes/invoices_.draft.$invoiceId_.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProposalsRoute = AiProposalsRouteImport.update({
  id: '/ai-proposals',
  path: '/ai-proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessGroupsRoute = BusinessGroupsRouteImport.update({
  id: '/business-groups',
  path: '/business-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationsRoute = ReconciliationsRouteImport.update({
  id: '/reconciliations',
  path: '/reconciliations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewAgentsRoute = ReviewAgentsRouteImport.update({
  id: '/review-agents',
  path: '/review-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdRoute = BillsBillIdRouteImport.update({
  id: '/bills_/$billId',
  path: '/bills/$billId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsCreateRoute = BillsCreateRouteImport.update({
  id: '/bills_/create',
  path: '/bills/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDepartmentIdRoute = DepartmentsDepartmentIdRouteImport.update({
  id: '/departments_/$departmentId',
  path: '/departments/$departmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents_/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesBanksRoute = EntitiesBanksRouteImport.update({
  id: '/entities/banks',
  path: '/entities/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesCustomersRoute = EntitiesCustomersRouteImport.update({
  id: '/entities/customers',
  path: '/entities/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEmployeesRoute = EntitiesEmployeesRouteImport.update({
  id: '/entities/employees',
  path: '/entities/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesGovernmentRoute = EntitiesGovernmentRouteImport.update({
  id: '/entities/government',
  path: '/entities/government',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesLendersRoute = EntitiesLendersRouteImport.update({
  id: '/entities/lenders',
  path: '/entities/lenders',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesShareholdersRoute = EntitiesShareholdersRouteImport.update({
  id: '/entities/shareholders',
  path: '/entities/shareholders',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesVendorsRoute = EntitiesVendorsRouteImport.update({
  id: '/entities/vendors',
  path: '/entities/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices_/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdRoute = LocationsLocationIdRouteImport.update({
  id: '/locations_/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsJoinRoute = OrganizationsJoinRouteImport.update({
  id: '/organizations/join',
  path: '/organizations/join',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxCertificatesRoute = TaxCertificatesRouteImport.update({
  id: '/tax/certificates',
  path: '/tax/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxComputeRoute = TaxComputeRouteImport.update({
  id: '/tax/compute',
  path: '/tax/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxSettingsRoute = TaxSettingsRouteImport.update({
  id: '/tax/settings',
  path: '/tax/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxDeadlinesRoute = TaxDeadlinesRouteImport.update({
  id: '/tax/deadlines',
  path: '/tax/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxEwtRoute = TaxEwtRouteImport.update({
  id: '/tax/ewt',
  path: '/tax/ewt',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxPartiesRoute = TaxPartiesRouteImport.update({
  id: '/tax/parties',
  path: '/tax/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRunIdRoute = PayrollRunIdRouteImport.update({
  id: '/payroll_/$runId',
  path: '/payroll/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationsReconciliationIdRoute =
  ReconciliationsReconciliationIdRouteImport.update({
    id: '/reconciliations_/$reconciliationId',
    path: '/reconciliations/$reconciliationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/transactions_/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions_/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsCategoryCategoryIdRoute =
  AccountsCategoryCategoryIdRouteImport.update({
    id: '/accounts_/category/$categoryId',
    path: '/accounts/category/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntitiesEntityTypePartyIdRoute =
  EntitiesEntityTypePartyIdRouteImport.update({
    id: '/entities/$entityType/$partyId',
    path: '/entities/$entityType/$partyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntitiesBanksBankIdRoute = EntitiesBanksBankIdRouteImport.update({
  id: '/entities/banks_/$bankId',
  path: '/entities/banks/$bankId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesDraftInvoiceIdRoute = InvoicesDraftInvoiceIdRouteImport.update({
  id: '/invoices_/draft/$invoiceId',
  path: '/invoices/draft/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesDraftCreateRoute = InvoicesDraftCreateRouteImport.update({
  id: '/invoices_/draft/create',
  path: '/invoices/draft/create',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPayInvoiceIdRoute = InvoicesPayInvoiceIdRouteImport.update({
  id: '/invoices_/pay/$invoiceId',
  path: '/invoices/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrgIdConnectionsRoute =
  OrganizationOrgIdConnectionsRouteImport.update({
    id: '/organization/$orgId/connections',
    path: '/organization/$orgId/connections',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationOrgIdMappingsRoute =
  OrganizationOrgIdMappingsRouteImport.update({
    id: '/organization/$orgId/mappings',
    path: '/organization/$orgId/mappings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationOrgIdSettingsRoute =
  OrganizationOrgIdSettingsRouteImport.update({
    id: '/organization/$orgId/settings',
    path: '/organization/$orgId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvoicesDraftInvoiceIdReviewRoute =
  InvoicesDraftInvoiceIdReviewRouteImport.update({
    id: '/invoices_/draft/$invoiceId_/review',
    path: '/invoices/draft/$invoiceId/review',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai-proposals': typeof AiProposalsRoute
  '/bills': typeof BillsRoute
  '/business-groups': typeof BusinessGroupsRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/departments': typeof DepartmentsRoute
  '/payroll': typeof PayrollRoute
  '/tax/certificates': typeof TaxCertificatesRoute
  '/tax/compute': typeof TaxComputeRoute
  '/tax/settings': typeof TaxSettingsRoute
  '/tax/deadlines': typeof TaxDeadlinesRoute
  '/tax/ewt': typeof TaxEwtRoute
  '/tax/parties': typeof TaxPartiesRoute
  '/documents': typeof DocumentsRoute
  '/financials': typeof FinancialsRoute
  '/inbox': typeof InboxRoute
  '/invoices': typeof InvoicesRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reconciliations': typeof ReconciliationsRoute
  '/review-agents': typeof ReviewAgentsRoute
  '/transactions': typeof TransactionsRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills/create': typeof BillsCreateRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/entities/banks': typeof EntitiesBanksRoute
  '/entities/customers': typeof EntitiesCustomersRoute
  '/entities/employees': typeof EntitiesEmployeesRoute
  '/entities/government': typeof EntitiesGovernmentRoute
  '/entities/lenders': typeof EntitiesLendersRoute
  '/entities/shareholders': typeof EntitiesShareholdersRoute
  '/entities/vendors': typeof EntitiesVendorsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/organizations/join': typeof OrganizationsJoinRoute
  '/payroll': typeof PayrollRoute
  '/tax/certificates': typeof TaxCertificatesRoute
  '/tax/compute': typeof TaxComputeRoute
  '/tax/settings': typeof TaxSettingsRoute
  '/tax/deadlines': typeof TaxDeadlinesRoute
  '/tax/ewt': typeof TaxEwtRoute
  '/tax/parties': typeof TaxPartiesRoute
  '/payroll/$runId': typeof PayrollRunIdRoute
  '/reconciliations/$reconciliationId': typeof ReconciliationsReconciliationIdRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/category/$categoryId': typeof AccountsCategoryCategoryIdRoute
  '/entities/$entityType/$partyId': typeof EntitiesEntityTypePartyIdRoute
  '/entities/banks/$bankId': typeof EntitiesBanksBankIdRoute
  '/invoices/draft/$invoiceId': typeof InvoicesDraftInvoiceIdRoute
  '/invoices/draft/create': typeof InvoicesDraftCreateRoute
  '/invoices/pay/$invoiceId': typeof InvoicesPayInvoiceIdRoute
  '/organization/$orgId/connections': typeof OrganizationOrgIdConnectionsRoute
  '/organization/$orgId/mappings': typeof OrganizationOrgIdMappingsRoute
  '/organization/$orgId/settings': typeof OrganizationOrgIdSettingsRoute
  '/invoices/draft/$invoiceId/review': typeof InvoicesDraftInvoiceIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai-proposals': typeof AiProposalsRoute
  '/bills': typeof BillsRoute
  '/business-groups': typeof BusinessGroupsRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/departments': typeof DepartmentsRoute
  '/payroll': typeof PayrollRoute
  '/tax/certificates': typeof TaxCertificatesRoute
  '/tax/compute': typeof TaxComputeRoute
  '/tax/settings': typeof TaxSettingsRoute
  '/tax/deadlines': typeof TaxDeadlinesRoute
  '/tax/ewt': typeof TaxEwtRoute
  '/tax/parties': typeof TaxPartiesRoute
  '/documents': typeof DocumentsRoute
  '/financials': typeof FinancialsRoute
  '/inbox': typeof InboxRoute
  '/invoices': typeof InvoicesRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reconciliations': typeof ReconciliationsRoute
  '/review-agents': typeof ReviewAgentsRoute
  '/transactions': typeof TransactionsRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills/create': typeof BillsCreateRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/entities/banks': typeof EntitiesBanksRoute
  '/entities/customers': typeof EntitiesCustomersRoute
  '/entities/employees': typeof EntitiesEmployeesRoute
  '/entities/government': typeof EntitiesGovernmentRoute
  '/entities/lenders': typeof EntitiesLendersRoute
  '/entities/shareholders': typeof EntitiesShareholdersRoute
  '/entities/vendors': typeof EntitiesVendorsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/organizations/join': typeof OrganizationsJoinRoute
  '/payroll': typeof PayrollRoute
  '/tax/certificates': typeof TaxCertificatesRoute
  '/payroll/$runId': typeof PayrollRunIdRoute
  '/reconciliations/$reconciliationId': typeof ReconciliationsReconciliationIdRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/category/$categoryId': typeof AccountsCategoryCategoryIdRoute
  '/entities/$entityType/$partyId': typeof EntitiesEntityTypePartyIdRoute
  '/entities/banks/$bankId': typeof EntitiesBanksBankIdRoute
  '/invoices/draft/$invoiceId': typeof InvoicesDraftInvoiceIdRoute
  '/invoices/draft/create': typeof InvoicesDraftCreateRoute
  '/invoices/pay/$invoiceId': typeof InvoicesPayInvoiceIdRoute
  '/organization/$orgId/connections': typeof OrganizationOrgIdConnectionsRoute
  '/organization/$orgId/mappings': typeof OrganizationOrgIdMappingsRoute
  '/organization/$orgId/settings': typeof OrganizationOrgIdSettingsRoute
  '/invoices/draft/$invoiceId/review': typeof InvoicesDraftInvoiceIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai-proposals': typeof AiProposalsRoute
  '/bills': typeof BillsRoute
  '/business-groups': typeof BusinessGroupsRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/departments': typeof DepartmentsRoute
  '/payroll': typeof PayrollRoute
  '/tax/certificates': typeof TaxCertificatesRoute
  '/documents': typeof DocumentsRoute
  '/financials': typeof FinancialsRoute
  '/inbox': typeof InboxRoute
  '/invoices': typeof InvoicesRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reconciliations': typeof ReconciliationsRoute
  '/review-agents': typeof ReviewAgentsRoute
  '/transactions': typeof TransactionsRoute
  '/bills_/$billId': typeof BillsBillIdRoute
  '/bills_/create': typeof BillsCreateRoute
  '/departments_/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/documents_/$documentId': typeof DocumentsDocumentIdRoute
  '/entities/banks': typeof EntitiesBanksRoute
  '/entities/customers': typeof EntitiesCustomersRoute
  '/entities/employees': typeof EntitiesEmployeesRoute
  '/entities/government': typeof EntitiesGovernmentRoute
  '/entities/lenders': typeof EntitiesLendersRoute
  '/entities/shareholders': typeof EntitiesShareholdersRoute
  '/entities/vendors': typeof EntitiesVendorsRoute
  '/invoices_/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/locations_/$locationId': typeof LocationsLocationIdRoute
  '/organizations/join': typeof OrganizationsJoinRoute
  '/payroll_/$runId': typeof PayrollRunIdRoute
  '/reconciliations_/$reconciliationId': typeof ReconciliationsReconciliationIdRoute
  '/transactions_/$transactionId': typeof TransactionsTransactionIdRoute
  '/transactions_/new': typeof TransactionsNewRoute
  '/accounts_/category/$categoryId': typeof AccountsCategoryCategoryIdRoute
  '/entities/$entityType/$partyId': typeof EntitiesEntityTypePartyIdRoute
  '/entities/banks_/$bankId': typeof EntitiesBanksBankIdRoute
  '/invoices_/draft/$invoiceId': typeof InvoicesDraftInvoiceIdRoute
  '/invoices_/draft/create': typeof InvoicesDraftCreateRoute
  '/invoices_/pay/$invoiceId': typeof InvoicesPayInvoiceIdRoute
  '/organization/$orgId/connections': typeof OrganizationOrgIdConnectionsRoute
  '/organization/$orgId/mappings': typeof OrganizationOrgIdMappingsRoute
  '/organization/$orgId/settings': typeof OrganizationOrgIdSettingsRoute
  '/invoices_/draft/$invoiceId_/review': typeof InvoicesDraftInvoiceIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/ai-proposals'
    | '/bills'
    | '/business-groups'
    | '/create-organization'
    | '/departments'
    | '/documents'
    | '/financials'
    | '/inbox'
    | '/invoices'
    | '/locations'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/reconciliations'
    | '/review-agents'
    | '/transactions'
    | '/bills/$billId'
    | '/bills/create'
    | '/departments/$departmentId'
    | '/documents/$documentId'
    | '/entities/banks'
    | '/entities/customers'
    | '/entities/employees'
    | '/entities/government'
    | '/entities/lenders'
    | '/entities/shareholders'
    | '/entities/vendors'
    | '/invoices/$invoiceId'
    | '/locations/$locationId'
    | '/organizations/join'
    | '/payroll/$runId'
    | '/reconciliations/$reconciliationId'
    | '/transactions/$transactionId'
    | '/transactions/new'
    | '/accounts/category/$categoryId'
    | '/entities/$entityType/$partyId'
    | '/entities/banks/$bankId'
    | '/invoices/draft/$invoiceId'
    | '/invoices/draft/create'
    | '/invoices/pay/$invoiceId'
    | '/organization/$orgId/connections'
    | '/organization/$orgId/mappings'
    | '/organization/$orgId/settings'
    | '/invoices/draft/$invoiceId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/ai-proposals'
    | '/bills'
    | '/business-groups'
    | '/create-organization'
    | '/departments'
    | '/documents'
    | '/financials'
    | '/inbox'
    | '/invoices'
    | '/locations'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/reconciliations'
    | '/review-agents'
    | '/transactions'
    | '/bills/$billId'
    | '/bills/create'
    | '/departments/$departmentId'
    | '/documents/$documentId'
    | '/entities/banks'
    | '/entities/customers'
    | '/entities/employees'
    | '/entities/government'
    | '/entities/lenders'
    | '/entities/shareholders'
    | '/entities/vendors'
    | '/invoices/$invoiceId'
    | '/locations/$locationId'
    | '/organizations/join'
    | '/payroll/$runId'
    | '/reconciliations/$reconciliationId'
    | '/transactions/$transactionId'
    | '/transactions/new'
    | '/accounts/category/$categoryId'
    | '/entities/$entityType/$partyId'
    | '/entities/banks/$bankId'
    | '/invoices/draft/$invoiceId'
    | '/invoices/draft/create'
    | '/invoices/pay/$invoiceId'
    | '/organization/$orgId/connections'
    | '/organization/$orgId/mappings'
    | '/organization/$orgId/settings'
    | '/invoices/draft/$invoiceId/review'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/ai-proposals'
    | '/bills'
    | '/business-groups'
    | '/create-organization'
    | '/departments'
    | '/documents'
    | '/financials'
    | '/inbox'
    | '/invoices'
    | '/locations'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/reconciliations'
    | '/review-agents'
    | '/transactions'
    | '/bills_/$billId'
    | '/bills_/create'
    | '/departments_/$departmentId'
    | '/documents_/$documentId'
    | '/entities/banks'
    | '/entities/customers'
    | '/entities/employees'
    | '/entities/government'
    | '/entities/lenders'
    | '/entities/shareholders'
    | '/entities/vendors'
    | '/invoices_/$invoiceId'
    | '/locations_/$locationId'
    | '/organizations/join'
    | '/payroll_/$runId'
    | '/reconciliations_/$reconciliationId'
    | '/transactions_/$transactionId'
    | '/transactions_/new'
    | '/accounts_/category/$categoryId'
    | '/entities/$entityType/$partyId'
    | '/entities/banks_/$bankId'
    | '/invoices_/draft/$invoiceId'
    | '/invoices_/draft/create'
    | '/invoices_/pay/$invoiceId'
    | '/organization/$orgId/connections'
    | '/organization/$orgId/mappings'
    | '/organization/$orgId/settings'
    | '/invoices_/draft/$invoiceId_/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AiProposalsRoute: typeof AiProposalsRoute
  BillsRoute: typeof BillsRoute
  BusinessGroupsRoute: typeof BusinessGroupsRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DocumentsRoute: typeof DocumentsRoute
  FinancialsRoute: typeof FinancialsRoute
  InboxRoute: typeof InboxRoute
  InvoicesRoute: typeof InvoicesRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ReconciliationsRoute: typeof ReconciliationsRoute
  ReviewAgentsRoute: typeof ReviewAgentsRoute
  TransactionsRoute: typeof TransactionsRoute
  BillsBillIdRoute: typeof BillsBillIdRoute
  BillsCreateRoute: typeof BillsCreateRoute
  DepartmentsDepartmentIdRoute: typeof DepartmentsDepartmentIdRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  EntitiesBanksRoute: typeof EntitiesBanksRoute
  EntitiesCustomersRoute: typeof EntitiesCustomersRoute
  EntitiesEmployeesRoute: typeof EntitiesEmployeesRoute
  EntitiesGovernmentRoute: typeof EntitiesGovernmentRoute
  EntitiesLendersRoute: typeof EntitiesLendersRoute
  EntitiesShareholdersRoute: typeof EntitiesShareholdersRoute
  EntitiesVendorsRoute: typeof EntitiesVendorsRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  LocationsLocationIdRoute: typeof LocationsLocationIdRoute
  OrganizationsJoinRoute: typeof OrganizationsJoinRoute
  PayrollRoute: PayrollRoute,
  TaxCertificatesRoute: TaxCertificatesRoute,
  TaxComputeRoute: typeof TaxComputeRoute
  TaxSettingsRoute: typeof TaxSettingsRoute
  TaxDeadlinesRoute: typeof TaxDeadlinesRoute
  TaxEwtRoute: typeof TaxEwtRoute
  TaxPartiesRoute: typeof TaxPartiesRoute
  PayrollRunIdRoute: typeof PayrollRunIdRoute
  ReconciliationsReconciliationIdRoute: typeof ReconciliationsReconciliationIdRoute
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  AccountsCategoryCategoryIdRoute: typeof AccountsCategoryCategoryIdRoute
  EntitiesEntityTypePartyIdRoute: typeof EntitiesEntityTypePartyIdRoute
  EntitiesBanksBankIdRoute: typeof EntitiesBanksBankIdRoute
  InvoicesDraftInvoiceIdRoute: typeof InvoicesDraftInvoiceIdRoute
  InvoicesDraftCreateRoute: typeof InvoicesDraftCreateRoute
  InvoicesPayInvoiceIdRoute: typeof InvoicesPayInvoiceIdRoute
  OrganizationOrgIdConnectionsRoute: typeof OrganizationOrgIdConnectionsRoute
  OrganizationOrgIdMappingsRoute: typeof OrganizationOrgIdMappingsRoute
  OrganizationOrgIdSettingsRoute: typeof OrganizationOrgIdSettingsRoute
  InvoicesDraftInvoiceIdReviewRoute: typeof InvoicesDraftInvoiceIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-proposals': {
      id: '/ai-proposals'
      path: '/ai-proposals'
      fullPath: '/ai-proposals'
      preLoaderRoute: typeof AiProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-groups': {
      id: '/business-groups'
      path: '/business-groups'
      fullPath: '/business-groups'
      preLoaderRoute: typeof BusinessGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliations': {
      id: '/reconciliations'
      path: '/reconciliations'
      fullPath: '/reconciliations'
      preLoaderRoute: typeof ReconciliationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-agents': {
      id: '/review-agents'
      path: '/review-agents'
      fullPath: '/review-agents'
      preLoaderRoute: typeof ReviewAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills_/$billId': {
      id: '/bills_/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof BillsBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills_/create': {
      id: '/bills_/create'
      path: '/bills/create'
      fullPath: '/bills/create'
      preLoaderRoute: typeof BillsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments_/$departmentId': {
      id: '/departments_/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof DepartmentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents_/$documentId': {
      id: '/documents_/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/banks': {
      id: '/entities/banks'
      path: '/entities/banks'
      fullPath: '/entities/banks'
      preLoaderRoute: typeof EntitiesBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/customers': {
      id: '/entities/customers'
      path: '/entities/customers'
      fullPath: '/entities/customers'
      preLoaderRoute: typeof EntitiesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/employees': {
      id: '/entities/employees'
      path: '/entities/employees'
      fullPath: '/entities/employees'
      preLoaderRoute: typeof EntitiesEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/government': {
      id: '/entities/government'
      path: '/entities/government'
      fullPath: '/entities/government'
      preLoaderRoute: typeof EntitiesGovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/lenders': {
      id: '/entities/lenders'
      path: '/entities/lenders'
      fullPath: '/entities/lenders'
      preLoaderRoute: typeof EntitiesLendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/shareholders': {
      id: '/entities/shareholders'
      path: '/entities/shareholders'
      fullPath: '/entities/shareholders'
      preLoaderRoute: typeof EntitiesShareholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/vendors': {
      id: '/entities/vendors'
      path: '/entities/vendors'
      fullPath: '/entities/vendors'
      preLoaderRoute: typeof EntitiesVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/$invoiceId': {
      id: '/invoices_/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations_/$locationId': {
      id: '/locations_/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/join': {
      id: '/organizations/join'
      path: '/organizations/join'
      fullPath: '/organizations/join'
      preLoaderRoute: typeof OrganizationsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/certificates': {
      id: '/tax/certificates'
      path: '/tax/certificates'
      fullPath: '/tax/certificates'
      preLoaderRoute: typeof TaxCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/compute': {
      id: '/tax/compute'
      path: '/tax/compute'
      fullPath: '/tax/compute'
      preLoaderRoute: typeof TaxComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/settings': {
      id: '/tax/settings'
      path: '/tax/settings'
      fullPath: '/tax/settings'
      preLoaderRoute: typeof TaxSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/deadlines': {
      id: '/tax/deadlines'
      path: '/tax/deadlines'
      fullPath: '/tax/deadlines'
      preLoaderRoute: typeof TaxDeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/ewt': {
      id: '/tax/ewt'
      path: '/tax/ewt'
      fullPath: '/tax/ewt'
      preLoaderRoute: typeof TaxEwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/parties': {
      id: '/tax/parties'
      path: '/tax/parties'
      fullPath: '/tax/parties'
      preLoaderRoute: typeof TaxPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll_/$runId': {
      id: '/payroll_/$runId'
      path: '/payroll/$runId'
      fullPath: '/payroll/$runId'
      preLoaderRoute: typeof PayrollRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliations_/$reconciliationId': {
      id: '/reconciliations_/$reconciliationId'
      path: '/reconciliations/$reconciliationId'
      fullPath: '/reconciliations/$reconciliationId'
      preLoaderRoute: typeof ReconciliationsReconciliationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/$transactionId': {
      id: '/transactions_/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/new': {
      id: '/transactions_/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/category/$categoryId': {
      id: '/accounts_/category/$categoryId'
      path: '/accounts/category/$categoryId'
      fullPath: '/accounts/category/$categoryId'
      preLoaderRoute: typeof AccountsCategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$partyId': {
      id: '/entities/$entityType/$partyId'
      path: '/entities/$entityType/$partyId'
      fullPath: '/entities/$entityType/$partyId'
      preLoaderRoute: typeof EntitiesEntityTypePartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/banks_/$bankId': {
      id: '/entities/banks_/$bankId'
      path: '/entities/banks/$bankId'
      fullPath: '/entities/banks/$bankId'
      preLoaderRoute: typeof EntitiesBanksBankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/draft/$invoiceId': {
      id: '/invoices_/draft/$invoiceId'
      path: '/invoices/draft/$invoiceId'
      fullPath: '/invoices/draft/$invoiceId'
      preLoaderRoute: typeof InvoicesDraftInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/draft/create': {
      id: '/invoices_/draft/create'
      path: '/invoices/draft/create'
      fullPath: '/invoices/draft/create'
      preLoaderRoute: typeof InvoicesDraftCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/pay/$invoiceId': {
      id: '/invoices_/pay/$invoiceId'
      path: '/invoices/pay/$invoiceId'
      fullPath: '/invoices/pay/$invoiceId'
      preLoaderRoute: typeof InvoicesPayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$orgId/connections': {
      id: '/organization/$orgId/connections'
      path: '/organization/$orgId/connections'
      fullPath: '/organization/$orgId/connections'
      preLoaderRoute: typeof OrganizationOrgIdConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$orgId/mappings': {
      id: '/organization/$orgId/mappings'
      path: '/organization/$orgId/mappings'
      fullPath: '/organization/$orgId/mappings'
      preLoaderRoute: typeof OrganizationOrgIdMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$orgId/settings': {
      id: '/organization/$orgId/settings'
      path: '/organization/$orgId/settings'
      fullPath: '/organization/$orgId/settings'
      preLoaderRoute: typeof OrganizationOrgIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/draft/$invoiceId_/review': {
      id: '/invoices_/draft/$invoiceId_/review'
      path: '/invoices/draft/$invoiceId/review'
      fullPath: '/invoices/draft/$invoiceId/review'
      preLoaderRoute: typeof InvoicesDraftInvoiceIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AiProposalsRoute: AiProposalsRoute,
  BillsRoute: BillsRoute,
  BusinessGroupsRoute: BusinessGroupsRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  DepartmentsRoute: DepartmentsRoute,
  DocumentsRoute: DocumentsRoute,
  FinancialsRoute: FinancialsRoute,
  InboxRoute: InboxRoute,
  InvoicesRoute: InvoicesRoute,
  LocationsRoute: LocationsRoute,
  PayrollRoute: PayrollRoute,
  TaxCertificatesRoute: TaxCertificatesRoute,
  TaxComputeRoute: TaxComputeRoute,
  TaxSettingsRoute: TaxSettingsRoute,
  TaxDeadlinesRoute: TaxDeadlinesRoute,
  TaxEwtRoute: TaxEwtRoute,
  TaxPartiesRoute: TaxPartiesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ReconciliationsRoute: ReconciliationsRoute,
  ReviewAgentsRoute: ReviewAgentsRoute,
  TransactionsRoute: TransactionsRoute,
  BillsBillIdRoute: BillsBillIdRoute,
  BillsCreateRoute: BillsCreateRoute,
  DepartmentsDepartmentIdRoute: DepartmentsDepartmentIdRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  EntitiesBanksRoute: EntitiesBanksRoute,
  EntitiesCustomersRoute: EntitiesCustomersRoute,
  EntitiesEmployeesRoute: EntitiesEmployeesRoute,
  EntitiesGovernmentRoute: EntitiesGovernmentRoute,
  EntitiesLendersRoute: EntitiesLendersRoute,
  EntitiesShareholdersRoute: EntitiesShareholdersRoute,
  EntitiesVendorsRoute: EntitiesVendorsRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  LocationsLocationIdRoute: LocationsLocationIdRoute,
  OrganizationsJoinRoute: OrganizationsJoinRoute,
  PayrollRunIdRoute: PayrollRunIdRoute,
  ReconciliationsReconciliationIdRoute: ReconciliationsReconciliationIdRoute,
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  AccountsCategoryCategoryIdRoute: AccountsCategoryCategoryIdRoute,
  EntitiesEntityTypePartyIdRoute: EntitiesEntityTypePartyIdRoute,
  EntitiesBanksBankIdRoute: EntitiesBanksBankIdRoute,
  InvoicesDraftInvoiceIdRoute: InvoicesDraftInvoiceIdRoute,
  InvoicesDraftCreateRoute: InvoicesDraftCreateRoute,
  InvoicesPayInvoiceIdRoute: InvoicesPayInvoiceIdRoute,
  OrganizationOrgIdConnectionsRoute: OrganizationOrgIdConnectionsRoute,
  OrganizationOrgIdMappingsRoute: OrganizationOrgIdMappingsRoute,
  OrganizationOrgIdSettingsRoute: OrganizationOrgIdSettingsRoute,
  InvoicesDraftInvoiceIdReviewRoute: InvoicesDraftInvoiceIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
